apiVersion: apps/v1
kind: Deployment
metadata:
  name: spacexapi
spec:
  selector:
    matchLabels:
      app: spacexapi
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 2
      maxUnavailable: 0
  replicas: 1
  template:
    metadata:
      labels:
        app: spacexapi
    spec:
      terminationGracePeriodSeconds: 15
      containers:
        - name: iss-api
          image: pastudan/iss-api
          imagePullPolicy: Always
          command: ['node', 'index.js']
          ports:
            - name: http-port
              containerPort: 8000
          resources:
            requests:
              cpu: 1m
              memory: 32Mi
            limits:
              cpu: 10m
              memory: 32Mi
